## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
# script:
#   - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("GroupSummaries"); Pkg.pkg"add Lazy#master"; Pkg.test("GroupSummaries"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("GroupSummaries")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("GroupSummaries")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
